force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Applied_Job__c.field-meta.xml
<CustomField>
    <fullName>Applied_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applied Job</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CandidateHelper.cls
public class CandidateHelper {
    
    public static void getCandidateCountByJob() {
        List<AggregateResult> results = [
            SELECT Applied_Job__c, COUNT(Id) total
            FROM Candidate__c
            GROUP BY Applied_Job__c
        ];
        
        for(AggregateResult ar : results) {
            System.debug('Job: ' + ar.get('Applied_Job__c') + 
                        ' | Total Candidates: ' + ar.get('total'));
        }
    }
}